### ISSUE TITLE
Concord T45

### ISSUE THREAD

**Issue by WhiskyTangoFawks** [WhiskyTangoFawks/LunarFalloutPlus#128]
Shorten warning
Script remove core
Drop helmet if condition greater than zero

**Comment by WhiskyTangoFawks** [comment]
Add a "Mangled Frame" item, which can potentially be repaired into a full PA Frame?

**Comment by TheGreatAuz** [comment]
I really like that last idea, especially if you could add it as a potential item to drop from enemies wearing power armor.
