### ISSUE TITLE
A minor and major suggestion

### ISSUE THREAD

**Issue by TheGreatAuz** [WhiskyTangoFawks/LunarFalloutPlus#133]
So having played through most of the game with this list and another I would like to make 2 suggestions from the other list that I believe both fit in and would round out the last few things (although I do recognize that some of this is subjective):

The first is this:
https://www.nexusmods.com/fallout4/mods/54138
It adds a device that can break down all of the various junk items, I recognize that this item is fairly powerful, but I would recommend adding it as the last benefit of the Scrapper perk (when I was playing your list the first time the last level of that perk level was completely not worth it, I believe a device like this would make it desirable)

The second is a couple of quest mods that have already been mentioned to you before I imagine... However, I do have some reasons if you're willing to hear them. While experimenting with a different list I had an opportunity to try some of these other quest mods and I have to agree that most are not necessarily worthy of addition, but both Fourville and The Secret of Huntress Manor I believe are the exceptions. They are both written by the same author as the Hilda Hughes and David Hunter mods and from what I played they had been voiced by some of the same people who did work for SS2 and I found the quality to be very in keeping. Those reasons aside I also believe there is a need for one more vault in the Commonwealth, as well as a story expanding on the Ug-Qualtoth concept which each of these mods does respectively. I know some of these reasons are personal taste but conceptually you and I share many of the same tastes in regards to modding, so I'm hoping you'd take some of what I have said seriously. The links to those to mods are:
https://www.nexusmods.com/fallout4/mods/43979
https://www.nexusmods.com/fallout4/mods/27311

**Comment by WhiskyTangoFawks** [comment]
THe scrapper thing is probably incompatible without me rewriting it completely, due to how it looks like it works with detecting awkcr.

Fourville is on my list of stuff to check. The secret of Huntress Manor I might check at some point, but my initial impression was that it doesn't really mesh into the lore of the game as well as the other mods. Like, it's not about vaults or the BoS or the Institute, it's about a random horror story.
