### ISSUE TITLE
Brown Face Bug

### ISSUE THREAD

**Issue by WhiskyTangoFawks** [WhiskyTangoFawks/LunarFalloutPlus#19]
Reported on
Cait (has custom face)
Piper (uses vanilla face)

**Comment by TheGreatAuz** [comment]
I just saw this and thought it might be appropriate (When I've seen this issue arise in my savegame it was after loading on death for any number of npc's)

https://www.nexusmods.com/fallout4/mods/31028

**Comment by WhiskyTangoFawks** [comment]
That's already included in the list
