### ISSUE TITLE
Discrepancy between default profiles

### ISSUE THREAD

**Issue by YoYoK3nny** [WhiskyTangoFawks/LunarFalloutPlus#266]
There's a slight discrepancy between the 2 provided profiles after a fresh install:

The following mods are enabled in the main profile, but disabled and unsorted in the CreationClubPaints profile.

- Institute EM Rifle
- Institute Plasma Rifle
- Lunar Fallout Overhaul - Institute Plasma Rifle
- Lunar Fallout Overhaul - Institute EM Rifle

It was easy to fix by switching between the profiles for the expected order.

Modlist version: 3.2.2

P.S: Thoughts on Locked Load Order? Would help with keeping the optionals in the correct order. The plugins should stay in right place even when the mod is disabled on the left

**Comment by WhiskyTangoFawks** [comment]
already fixed for the next upload. I'm not really worried about locked load order, it's not really an issue most of the time.
