### ISSUE TITLE
Ada is a Guy now?

### ISSUE THREAD

**Issue by slaughter2012** [WhiskyTangoFawks/LunarFalloutPlus#268]
Issue 1. Ada is a guy now and not a robot, no clothes on either.
Issue 2. Ada can not be fitted with the Radar Beacon via the robot work bench.

**Comment by slaughter2012** [comment]
![ada](https://user-images.githubusercontent.com/83192115/224935901-84917528-bb80-4bed-9d6b-a09ee7899a99.jpg)

**Comment by WhiskyTangoFawks** [comment]
Yeah, I don't know what you're running, but based on that photo it's definitely not stock LitR. I've verified that Ada works as expected on my end. This is a problem with the modifications you've made to your load order.

My recommendation to fix, if you don't want to do conflict resolution with whatever mods you've added, it is to revert to stock LitR.

**Comment by slaughter2012** [comment]
No other mods added🙂 Just thought I'd show you 😎. I'll do a full
reinstall, usually sorts things out. I'll keep the save, it should be ok😎👍
