### ISSUE TITLE
PJAR Makeshift Pistol - data corrupted

### ISSUE THREAD

**Issue by serek001** [WhiskyTangoFawks/LunarFalloutPlus#270]
That mod have files corrupted on Nexus or something is wrong with hashes. I tried redowloading for 3 times.
[https://www.nexusmods.com/fallout4/mods/45131?tab=files](url)

Wabbajack log line:
`
[ERROR] (Wabbajack.InstallerVM) File F:\LifeInRuinsModlist\downloads\PJAR Makeshift Pistol-45131-1-1-1589873390.rar|PJARPistol - Textures.ba2 is corrupt, please delete it and retry the installation, Hashes for TEMP_BSA_FILES\f2d59764-b08a-4fbf-ae9e-37b887d368c6\textures\weapons\pjarpistol\cubemaps\metalbrushed02cube_e.dds did not match, expected xPgEu2RZkz4= got tzP+pj4Ca44=|System.Exception: File F:\LifeInRuinsModlist\downloads\PJAR Makeshift Pistol-45131-1-1-1589873390.rar|PJARPistol - Textures.ba2 is corrupt, please delete it and retry the installation, Hashes for TEMP_BSA_FILES\f2d59764-b08a-4fbf-ae9e-37b887d368c6\textures\weapons\pjarpistol\cubemaps\metalbrushed02cube_e.dds did not match, expected xPgEu2RZkz4= got tzP+pj4Ca44=
`

**Comment by WhiskyTangoFawks** [comment]
That mod is not included in the most recent releases of the list.
