### ISSUE TITLE
Wishlist - Differentiate gameplay for institute lasers 

### ISSUE THREAD

**Issue by WhiskyTangoFawks** [WhiskyTangoFawks/LunarFalloutPlus#28]
Lasers and the institute laser feel the same

Laser musket - slow, high damage
Laser - moderate, moderate damage?
Institute laser - fast, low damage?

**Comment by TheGreatAuz** [comment]
I just had a thought that maybe you could implement here, I would use the Gamma wave effect to make the institute lasers have a slower "bullet" speed, with a high fire rate, and then moderate damage. That would help make the Institute lasers really feel different, and as a faction they use other Gamma gun mods on their weapons more commonly than any other faction so it would fit right in with their other aesthetics. I might change the wave color, but other than that I think it would work pretty well.
