### ISSUE TITLE
Bugfix- SS2 "Gone Fishing" location

### ISSUE THREAD

**Issue by TheGreatAuz** [WhiskyTangoFawks/LunarFalloutPlus#66]
In my current playthrough I have experienced two bug-ish type issues with this modlist. One is likely easy to fix as it appears to be some kind of precombine issue, the other is a little trickier...

The first issue is with a quest added by SS2 Chapter 1, I believe the quest is called "Gone Fishing" where you get a distress radio broadcast in the middle of the Glowing Sea. The factory location that the broadcast sends you to has been modified by SS2 for this quest, but the game doesn't seem to recognize that there's no ground or a hole in the wall at the appropriate moments. I had to TCL through nothing twice in order to complete this quest.

The second issue is a little broader and less specific. At the South Boston Red Rocket the Scavver faction was wiped out by roving Super Mutants, this part doesn't bother me too much, however now that nobody controls that Workbench I cannot fast travel there even though I have the Perk that should allow me to do so. I can take control of the Workbench myself, but it is not a fully functional workbench and will not allow me to build a radio beacon or defenses. I would suggest that the Scavvers simply respawn after a few days and the workbench be completely removed from the equation, but I would also find it acceptable to have to rebuild the outpost after it had been destroyed. As long as the ability to fast travel there isn't blocked after all of the Scavvers being killed.

I have also had an issue that appears to be a little more common with SS2 Chapter 2 where I cannot progress past the How to HQ quest because the option to start a supply contract doesn't appear in my Workshop mode screen. I have done everything I know how to do to fix this issue but to no avail. As I said this appears to be an issue with Chapter 2 itself so I didn't consider it to be an incompatibility.

**Comment by WhiskyTangoFawks** [comment]
The Scavver faction is set to unspawnable by the mod author on purpose, and I am reluctant to mess with SKKs mods. I think the fast travel thing is causing other bugs as well, so that might need a fix.

**Comment by TheGreatAuz** [comment]
Update: I have since fixed my primary SS2C2 issue by digging into the Global Variables and finding the one which did not correctly activate and switching it on. And the reported issue of the workshop not working correctly is still slightly true, but not as correct as reported. That specific workshop (South Boston Red Rocket) is very sluggish and doesn't seem to respond well to things being loaded into it. This created at one time the illusion that I could not build a radio beacon, but I have now done so and it seems to mostly be working as a settlement, however I still cannot fast travel there as I can to the Sanctuary Hills Red Rocket. I would suggest looking to see if the workshop is implemented correctly and is it using the updated scripts from Workshop Framework.
