### ISSUE TITLE
Minor Atom Cats Issue

### ISSUE THREAD

**Issue by TheGreatAuz** [WhiskyTangoFawks/LunarFalloutPlus#81]
Some of the Atom Cats are not wearing clothes in my save, most notably the bartender and the leader guy (Zeke? I don't remember his name right now, but he's the guy that gives you your Atom Cats clothes.) The leader is usually in power armor so I didn't notice at first, but the Bartender guy almost never is. I almost never really go there so it isn't a huge deal for me and it took me a while to notice, but I figured you'd want to know.

**Comment by WhiskyTangoFawks** [comment]
This was resolved in 1.0.3. Unfortunatly, it will only take effect when the cell resets, or on a new game if you've updated. If this was in a new game started with 1.0.3 or after let me know and I'll reopen.
