### ISSUE TITLE
Question/Possible Redundancy

### ISSUE THREAD

**Issue by TheGreatAuz** [WhiskyTangoFawks/LunarFalloutPlus#82]
So I noticed that the last update included this mod Journey, I am mostly confused by this change because this functionality is essentially included in Sim Settlements 2 (after your caravan plot reaches level 2 you can talk to the caravanner and they'll take you to any connected settlement.) So I am wondering why it was added or what functions or options it adds that are not included in Sim Settlements but that you want to be available?

Sorry if I'm being presumptuous, it just threw me off.

**Comment by WhiskyTangoFawks** [comment]
This isn't an issue report so I'm going to close it.

There is information on this topic in the readme, and in the changelog. Issue reports are great for adding stuff to my todo list, but if you have further questions like this, the discord is a better place for it.
